[workspace]
channels = ["conda-forge"]
name = "tbot"
platforms = ["linux-64", "win-64"]
preview = ["pixi-build"]
version = "0.1.0"


[tasks]


[dependencies]
python = ">=3.13.3,<3.14"
beautifulsoup4 = ">=4.13.3,<5"
elasticsearch = ">=8.17.2,<9"
debugpy = ">=1.8.15,<2"
python-dotenv = ">=1.0.1"
aiohttp=">=1.0"
requests=">=1.0"

[pypi-dependencies]
python-telegram-bot=">=21.7"
nest_asyncio = ">=1.6.0"
mysql-connector-python=">=9.1.0"
ymaps=">=1.3"
google-api-python-client=">=2.156.0"
telegramify-markdown =">=0.3.1"